services:
  # 服务1：数据库（MySQL）
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root1234      # 数据库密码
      MYSQL_DATABASE: ai_chat_app        # 自动创建的库名
    ports:
      - "3307:3307"                      # 映射到本机 3306 端口
    volumes:
      - mysql_data:/var/lib/mysql        # 数据持久化（关掉容器数据不丢）
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 服务2：你的 FastAPI 应用
  app:
    build:
       context: .
       dockerfile: docker/Dockerfile                            # 根据此目录的 Dockerfile 构建
    ports:
      - "8000:8000"                      # 映射到本机 8000 端口
    depends_on:
      db:
        condition: service_healthy       # 等数据库完全启动后再启动应用
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # 关键：数据库地址！ 主机名写 db（服务名），而不是 localhost
      - DATABASE_URL=mysql+pymysql://root:root1234@db:3306/ai_chat_app
      - OLLAMA_URL=http://host.docker.internal:11434/api/chat

volumes:
  mysql_data:                            # 声明一个数据卷，用于存放 MySQL 真实数据