"""add index on owner

Revision ID: a2e24aa681a8
Revises: be9e1eef3dd3
Create Date: 2026-07-20 09:26:14.254855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e24aa681a8'
down_revision: Union[str, Sequence[str], None] = 'be9e1eef3dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_owner'), 'sessions', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_owner'), table_name='sessions')
    # ### end Alembic commands ###
